Basic Auth and verify Done.

diff --git a/github/workflows/main_ci_cd.yml b/github/workflows/main_ci_cd.yml
--- a/github/workflows/main_ci_cd.yml
+++ b/github/workflows/main_ci_cd.yml
@@ -34,7 +34,7 @@ jobs:
 
       - uses: actions/setup-python@v6
         with:
-          python-version: "3.12"
+          python-version: "3.13"
 
       - name: Install dependencies
         run: |
@@ -53,12 +53,12 @@ jobs:
         run: |
           cp .env.ci.example .env
 
-      # - name: Check migrations
-      #   run: python manage.py makemigrations --check --dry-run
+      - name: Check migrations
+        run: python manage.py makemigrations --check --dry-run
       # OR
-      - name: Run migrations
-        run: |
-          python manage.py test
+      # - name: Run migrations
+      #   run: |
+      #     python manage.py test
 
       - uses: docker/setup-buildx-action@v3
 
@@ -103,11 +103,22 @@ jobs:
           script: |
             set -e
             cd ${{ env.VPS_PROJECT_DIRECTORY }}
+            
+            # Remove all existing images for this Docker image
+            EXISTING_IMAGES=$(docker images -q ${{ env.DOCKER_IMAGE }})
+            if [ -n "$EXISTING_IMAGES" ]; then
+                echo "Removing existing images for ${{ env.DOCKER_IMAGE }}..."
+                docker rmi -f $EXISTING_IMAGES || true
+            fi
+            
+            # Retry pulling the new image
             COUNT=0
             until docker pull ${{ env.DOCKER_IMAGE }}:${{ github.sha }} || [ $COUNT -eq ${{ env.MAX_RETRIES }} ]; do
                 echo "Waiting for image to appear in registry..."
                 sleep ${{ env.RETRY_DELAY }}
                 COUNT=$((COUNT + 1))
             done
+            
+            # Restart Docker Compose
             docker compose -f ${{ env.COMPOSE_FILE }} down
             IMAGE_TAG=${{ github.sha }} docker compose -f ${{ env.COMPOSE_FILE }} up -d
